env:
  node: true
parseOptions:
  ecmaVersion: 6
  sourceType: module
# extends: 'eslint:recommended'
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - google
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  no-unused-vars:
    - warn
  comma-style:
    - error
    - last
  no-var:
    - off
