env:
  es6: true
  browser: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
settings:
  import/resolver: node
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - google
rules:
  indent:
    - error
    - 2
    - ObjectExpression: 'first'
  linebreak-style:
    - error
    - unix
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  no-unused-vars:
    - warn
  comma-style:
    - error
    - last
  comma-dangle:
    - error
    - never
