version: '2'

services:
  web:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - .:/www/
      - ./nginx.conf:/etc/nginx/nginx.conf
  xmpp:
    build: prosody
    ports:
      - 5222:5222
    command:
      prosodyctl start
